# Generated by Django 5.2.1 on 2025-05-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=50)),
                ('lokal', models.CharField(max_length=20)),
                ('uprava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisustvo.uprava')),
            ],
        ),
        migrations.CreateModel(
            name='PrisustvoNaDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('status', models.CharField(choices=[('+', 'Prisutan'), ('Го', 'Godišnji odmor'), ('Д', 'Dežurstvo'), ('Б', 'Bolovanje'), ('С', 'Slobodan'), ('Н', 'Neopravdano'), ('Р', 'Rad od kuće'), ('О', 'Odsutan')], max_length=5)),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisustvo.zaposleni')),
            ],
            options={
                'unique_together': {('zaposleni', 'datum')},
            },
        ),
        migrations.CreateModel(
            name='PrisustvoMesec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField()),
                ('mesec', models.IntegerField()),
                ('dan', models.IntegerField()),
                ('status', models.CharField(max_length=5)),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisustvo.zaposleni')),
            ],
            options={
                'unique_together': {('zaposleni', 'godina', 'mesec', 'dan')},
            },
        ),
    ]
