# Generated by Django 5.2.1 on 2025-05-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisustvo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisustvomesec',
            name='status',
            field=models.CharField(choices=[('+', 'Prisutan na poslu'), ('Го', 'Godišnji odmor'), ('Д', 'Dežurstvo'), ('Дс', 'Slobodan dan posle dež.'), ('Со', 'Službeno odsutan'), ('Бо', 'Bolovanje'), ('Сп', 'Službeni put'), ('Лп', 'Lekarski pregled'), ('Опп', 'Privatni poslovi'), ('Н', 'Nepoznato do 08:55'), ('Сд', 'Slobodan dan'), ('Дк', 'Dolazi kasnije'), ('Оо', 'Ostala odsustva do 7 dana'), ('Но', 'Nagradno odsustvo'), ('Оп', 'Obilazak porodice'), ('Рок', 'Rad od kuće'), ('Упп', 'Ugovor o priv. poslovima')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prisustvonadan',
            name='status',
            field=models.CharField(choices=[('+', 'Prisutan na poslu'), ('Го', 'Godišnji odmor'), ('Д', 'Dežurstvo'), ('Дс', 'Slobodan dan posle dež.'), ('Со', 'Službeno odsutan'), ('Бо', 'Bolovanje'), ('Сп', 'Službeni put'), ('Лп', 'Lekarski pregled'), ('Опп', 'Privatni poslovi'), ('Н', 'Nepoznato do 08:55'), ('Сд', 'Slobodan dan'), ('Дк', 'Dolazi kasnije'), ('Оо', 'Ostala odsustva do 7 dana'), ('Но', 'Nagradno odsustvo'), ('Оп', 'Obilazak porodice'), ('Рок', 'Rad od kuće'), ('Упп', 'Ugovor o priv. poslovima')], max_length=10),
        ),
    ]
