# Generated by Django 5.2.1 on 2025-05-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisustvo', '0002_alter_prisustvomesec_status_and_more'),
        ('prisustvo', '0002_zaposleni_user'),
    ]

    operations = [
    ]
