# Generated by Django 5.2.1 on 2025-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisustvo', '0003_merge_20250527_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisustvomesec',
            name='status',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='prisustvonadan',
            name='status',
            field=models.CharField(choices=[('+', 'Prisutan'), ('Го', 'Godišnji odmor'), ('Д', 'Dežurstvo'), ('Б', 'Bolovanje'), ('С', 'Slobodan'), ('Н', 'Neopravdano'), ('Р', 'Rad od kuće'), ('О', 'Odsutan')], max_length=5),
        ),
    ]
