# Generated by Django 5.2.1 on 2025-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisustvo', '0005_alter_prisustvonadan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisustvonadan',
            name='status',
            field=models.CharField(choices=[('Го', 'Godišnji odmor'), ('Д', 'Dežurstvo'), ('Дс', 'Slobodan dan dež.'), ('Со', 'Služ. odsut. van upr.'), ('Бо', 'Bolovanje'), ('Сп', 'Službeni put'), ('Лп', 'Lekarski pregled'), ('Опп', 'Ostali privatni poslovi'), ('Н', 'Nepoznato do 07:55'), ('Сд', 'Slobodan dan'), ('Оо', 'Ost. odsustvo do 7 dana'), ('Но', 'Nagradno odsustvo'), ('Оп', 'Obilazak porodice'), ('Рок', 'Rad od kuće'), ('ПУ', 'Priv. upućeni van uprave'), ('УоД', 'Ugovor o delu'), ('Упп', 'Ugovor o priv. pov. poslovima')], max_length=10),
        ),
    ]
