# Generated by Django 5.2.1 on 2025-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisustvo', '0006_alter_prisustvonadan_status'),
    ]

    operations = [
       migrations.AlterField(
            model_name='prisustvonadan',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
